### ISSUE TITLE
undefined method `will_save_change_to_email?' for User

### ISSUE THREAD

**Issue by mtoribio** [heartcombo/devise#4542]
Hi,
I have problems with:
- Devise 4.3
- Rails 5.1
- Mongoid 6.1
```
NoMethodError (undefined method `will_save_change_to_email?' for #<User:0x007f80b1778ec0>):
  
activesupport (5.1.1) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.1) lib/active_support/callbacks.rb:177:in `block (2 levels) in halting_and_conditional'
activesupport (5.1.1) lib/active_support/callbacks.rb:177:in `each'
activesupport (5.1.1) lib/active_support/callbacks.rb:177:in `all?'
activesupport (5.1.1) lib/active_support/callbacks.rb:177:in `block in halting_and_conditional'
activesupport (5.1.1) lib/active_support/callbacks.rb:507:in `block in invoke_before'
activesupport (5.1.1) lib/active_support/callbacks.rb:507:in `each'
activesupport (5.1.1) lib/active_support/callbacks.rb:507:in `invoke_before'
activesupport (5.1.1) lib/active_support/callbacks.rb:130:in `run_callbacks'
mongoid (6.1.0) lib/mongoid/interceptable.rb:138:in `run_callbacks'
activesupport (5.1.1) lib/active_support/callbacks.rb:825:in `_run_validate_callbacks'
activemodel (5.1.1) lib/active_model/validations.rb:405:in `run_validations!'
activemodel (5.1.1) lib/active_model/validations/callbacks.rb:110:in `block in run_validations!'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
mongoid (6.1.0) lib/mongoid/interceptable.rb:138:in `run_callbacks'
activesupport (5.1.1) lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
activemodel (5.1.1) lib/active_model/validations/callbacks.rb:110:in `run_validations!'
activemodel (5.1.1) lib/active_model/validations.rb:335:in `valid?'
mongoid (6.1.0) lib/mongoid/validatable.rb:97:in `valid?'
activemodel (5.1.1) lib/active_model/validations.rb:372:in `invalid?'
mongoid (6.1.0) lib/mongoid/persistable/creatable.rb:115:in `prepare_insert'
mongoid (6.1.0) lib/mongoid/persistable/creatable.rb:23:in `insert'
mongoid (6.1.0) lib/mongoid/persistable/savable.rb:23:in `save'
/Volumes/FdData/Users/mToribio/.rvm/gems/ruby-2.4.1/bundler/gems/devise_token_auth-73d82dbd0982/app/controllers/devise_token_auth/registrations_controller.rb:42:in `create'
actionpack (5.1.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.1) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
In rails 5.0 thats works good.
I have been investigating a little more and I not found where is defined *will_save_change_to_email?*.
I think thats could be the problem...
For now, I will use Rails 5.0 but I would like use Rails 5.1.

Thanks in advance.

**Comment by aalbagarcia** [comment]
I have the same problem. I'm using mongoid 6.1 **and** Active Record. According to the comment in [3e1c9e3](https://github.com/plataformatec/devise/commit/3e1c9e343ce537e3c9aabd74592e375152482045) it's nor working at the moment. Also related to [this issue](https://github.com/plataformatec/devise/issues/4531).

**Comment by codewizardry** [comment]
I am not sure what exactly transpired to have caused this error. It seems that all of a sudden I'm getting the same `Undefined method `will_save_change_to_email?' for User` error.  So, a quick monkey patch, at least for the time being, is to just define `will_save_change_to_email?` in the model, in my particlar case, the model was User, so I defined it in there as follows:

```
def will_save_change_to_email?
end
```

This resolves the problem, at least in my case it did. 

The issue here is that method 

```
def will_save_change_to_email?
end
```

is not even defined in the devise gem.

Although it is referenced in the callback, in the following files:

> 
> lib/devise/models/confirmable.rb
> lib/devise/models/validatable.rb
> 
> and 
> 
> test/rails_app/lib/shared_admin.rb

it is not defined whatsoever.

Please note that this problem is only raised and repliacted when using Mongoid as of today's date, 7/9/2017. 

The problem does not exist when using Active Record.

**Comment by chrise86** [comment]
I've facing this issue with ActiveRecord.

```
rails (5.1.2)
devise (4.3.0)
```

**Comment by codewizardry** [comment]
Do you have the mongoid gem installed? You probably do, as one could still have both, Active Record and Mongoid in the same app.  I don't think the issue is stemming from Active Record, if that was the case, then a significant amount of Rails apps would break, and it would have been resolved a long time ago, I'm not sure if its from Devise either.  I think this is stemming from mongoid!?  At any rate, did you define the method `will_save_change_to_email?` in your model?   For me, all I did is simply define it in my model like this:

`def will_save_change_to_email?
end`

And it worked like a charm. 

I'm using:

`
Rails (5.1.2)
Devise (4.3.0)
Mongoid (6.2.0)
ActiveRecord (5.1.2)
`

**Comment by chrise86** [comment]
So it turns out that the model does not have an email attribute, and both `email_required?` and `email_changed?` had been defined inside the model to negate the validation in previous versions.

The project is one I've inherited and had the please of taking from Rails 3 all the way up to 5.1, while switching from MySQL to Postgresql. It's been, interesting...

**Comment by tegon** [comment]
Hello @mtoribio, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by nao215** [comment]
I got a same error.

My environment is below.
```
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin16]
rails (5.1.4)
devise (4.3.0)
```
I dont use mongoid, Im using mysql.

And the table we use for devise doesnt have column the name of 'email'.
I think you can reproduce this error by creating app using devise without using email column.

Sorry I dont have time to create public repo, but I wish this will help you.

**Comment by tegon** [comment]
@nao215 what devise modules are you using in your model? [validatable](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/models/validatable.rb#L33) requires an email attribute and we also call this method on [confirmable](https://github.com/plataformatec/devise/blob/8c9cc8d355825e2b7ae0b4dcdedee518831e3338/lib/devise/models/confirmable.rb#L279) (but I guess you don't use confirmable since you don't have an email column)

**Comment by nao215** [comment]
```
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable,
         authentication_keys: [:agency_email]
```

```
  config.case_insensitive_keys = [ :agency_email ]
  config.strip_whitespace_keys = [ :agency_email ]
  config.confirmation_keys = [ :agency_email ]
  config.reset_password_keys = [ :agency_email ]
```

this is our code for devise.
Sorry, I have a lot of client and it was just quick look.

The error happened when we try to up rails version to 5.
I guess

**Comment by tegon** [comment]
@nao215 But even when you hit the `else` clause, the method `email_changed?` will be called. If you don't have that column I guess this method doesn't exist on your model too, right?

**Comment by nao215** [comment]
@tegon 
> But even when you hit the else clause, the method email_changed? will be called.
Yes, but the error is `undefined method 'will_save_change_to_email?'` not `email_changed?`.
I cant find definition of `will_save_change_to_email` but this is looks like auto generated method so I guess if we dont use column name of email, not generated. ※ just I guess

**Comment by tegon** [comment]
@nao215 What I meant is that is weird this worked before you update rails, because even though `Devise.activerecord51?` returns `false`, the method `will_save_change_to_email?` won't be called, but `email_changed?` would. Does your model responds to `email_changed?`?

**Comment by mbell697** [comment]
I've run into this as well.

The problem appears to be that devise only makes a global check for `Devise.activerecord51?` without consulting which ORM is actually storing the `User` model. In our case the `User` model is backed by Mongoid 6.4.1, not ActiveRecord. So devise is trying to call AR methods on a mongoid model which doesn't support them.

**Comment by tegon** [comment]
@mbell697 Can you provide us a sample application that reproduces the issue in isolation?
Another option is to use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

**Comment by mbell697** [comment]
@tegon If you modify your test suite to load both Mongoid and ActiveRecord, but test Mongoid backed device models, you'll likely see a bunch of failures. Can probably just make a quick change here (https://github.com/plataformatec/devise/blob/master/test/rails_app/config/application.rb#L12) to always load active record and run the suite with `DEVISE_ORM=mongoid`.

**Comment by doughsay** [comment]
I ran into this as well, from a clean new rails application.

STR:

1.) rails new auth_test
2.) add and configure mongoid
3.) add and configure devise
4.) generate new User model using devise generator (generates a mongoid model)
5.) can't sign up (`undefined method `will_save_change_to_email?' for User`)

You can fix this problem by not including ActiveRecord: `rails new auth_test -O`

**Comment by tegon** [comment]
Related sample application 
https://github.com/plataformatec/devise/pull/4910#issuecomment-413359139

**Comment by theshashiverma** [comment]
@mtoribio @aalbagarcia @codewizardry @chrise86 @tegon  please have a look on this https://github.com/plataformatec/devise/issues/5017

**Comment by chrisokamoto** [comment]
I am still face problem with mthis.. I am using 
- rails 5.1.7
- devise 4.6.2
- activerecord 5.1.7
- mongoid 6.1.0

I need both mongoid and activerecord on my system.. the User class uses mongoid and has a field called email. Everything was working perfectly on rails 5.0 but since I updated Rails to 5.1.7 I get this message `undefined method `will_save_change_to_email?'`. I tried doind what it was suggested here on this thread, creating a method called `will_save_change_to_email?` on User.rb. but the expected behaviour is still not right. For example, when the user changes his email, Devise is not sending the email for the user to confirm his email again. Instead I just see a notice message saying that my data was updated, which means that I see the registrations.updated message instead of registrations.update_needs_confirmation message. 

Any updates on this?

**Comment by tegon** [comment]
@chrisokamoto Unfortunately, I haven't been able to dig deep into this yet. I'll try to do it soon.

**Comment by chrisokamoto** [comment]
setting this 3 aliases "solved" the problem for me for now:

> alias will_save_change_to_email? email_changed?
> alias email_in_database email_was
> alias email_before_last_save email_before_destroy_was

**Comment by rp-pedraza** [comment]
I define `email` as a virtual attribute and I found out that I need to call [define_attribute_method](https://api.rubyonrails.org/classes/ActiveModel/AttributeMethods/ClassMethods.html#method-i-define_attribute_method) with it.

Default prefixes and suffixes are defined in `ActiveRecord::AttributeMethods::Dirty`.  `ActiveModel::AttributeMethods` is also already included by `ActiveRecord::AttributeMethods`, which is also included by `ActiveRecord::Base`. Rails version 6.0.0.

**Comment by apoorv-1310** [comment]
create a function in model file

` def will_save_change_to_email?
    false
  end`

**Comment by vanboom** [comment]
For info...
I just upgrade an app from Rails 5.2.4.3 (which does not exhibit this issue) to 5.2.4.5 and this error appeared.  I am using Mongoid for database and thought I inhibited the ActiveRecord per the Mongoid instructions. 

In Rails 5.2.4.3:  
```
defined?(ActiveRecord)
> nil
```
In Rails 5.2.4.5
```
defined?(ActiveRecord)
> "constant"
```

This appears to be causing Devise.activerecord51? to be `true` and the root cause of the undefined method `will_save_change_to_email?` error.

**Comment by vanboom** [comment]
After removing `spring` from Gemfile, this issue still occurs: 

Under Rails 5.2.4.3, defined?(ActiveRecord) returns `nil`
Under Rails 5.2.4.5, defined?(ActiveRecord) returns `true`

**Comment by SaimonL** [comment]
DEVICE GEM IS WORKING FINE NO ISSUE AT ALL

Here is my following setup

Rails 5.2.6
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
mongoid (7.0.13)
devise (4.8.0)
devise-encryptable (0.2.0)

In file "config/initializers/devise.rb"
```ruby
require 'devise/orm/mongoid'
```

## Problem

Device thinks you are using ActiveRecord even though you have created your rails application with the option `--skip-active-record`. 

## Why

You have a gem that is not compatible with mongoid and is using ActiveRecord monkey patching.

## How 

When device try to detect if you are using  ActiveRecord be using the code below

```ruby
defined?(ActiveRecord) && ActiveRecord.gem_version >= Gem::Version.new("5.1.x")
```

it comes up false positive.

## Solution

Enter rails console and type in `ActiveRecord` and you should see error message:

```ruby
NameError: uninitialized constant ActiveRecord
from (pry):13:in `<main>'
```

If you don't then start removing gems until you see that message. 

For me it was there following gems that gave me grief: 
* crono
* delayed_job_web
* database_cleaner

I replaced "cromo" with "whenever", "database_cleaner" with "database_cleaner-mongoid"

**Comment by carlosantoniodasilva** [comment]
@SaimonL what you explained here makes sense to me.

Is anyone still having this kind of issue? Please let me know so I can try to take another look, otherwise I'm gonna close it in a week or two.

**Comment by mbell697** [comment]
Yes - the behavior is still the same. 

What @SaimonL described is a possible trigger, but in our case it's much simpler - our application uses both Mongoid and ActiveRecord. 

At the base level, the problem is that Devise currently checks for the presence of the `ActiveRecord` gem to determine how to behave: https://github.com/heartcombo/devise/blob/8e2e3f6fda1ceabe2eff08cf34a6e663527c438b/lib/devise.rb#L311

This drives a lot of choices down stream, e.g. https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/devise/models/database_authenticatable.rb#L208

The problem is that the presence of the `ActiverRecord` gem doesn't mean that any given user model is an `ActiveRecord` model. The better approach would be to check each user model to determine if it's an AR model or a Mongoid model and react accordingly.

**Comment by carlosantoniodasilva** [comment]
@mbell697 thanks for the information, I think that makes sense. I believe Devise never considered being used in an app that has both ORMs loaded -- even though I think it'd be possible to even use Devise in both at the same time by requiring both ORMs at the initializer.

> The better approach would be to check each user model to determine if it's an AR model or a Mongoid model and react accordingly.

Sounds like this could work yeah, I will see if I can look into some changes there. I want to get Devise running tests with latest versions of Mongo as well at some point.

**Comment by carlosantoniodasilva** [comment]
Okay, I have a possible fix for this scenario with multiple ORMs loaded in https://github.com/heartcombo/devise/pull/5576, and I'm also working to reenable Mongoid tests in https://github.com/heartcombo/devise/pull/5568 (it's all green up to Mongoid 7.x, but Mongoid 8 will need some additional work as it apparently introduced changes to dirty tracking as well)

That should be enough to fix these issues I hope.
